# Generated by Django 4.2.2 on 2024-05-31 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [("can_deactivate_user", "Can deactivate user")],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
